import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageHeader from "@/components/page-header";
import PageFooter from "@/components/page-footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "JOI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} flex flex-col min-h-screen pl-24 pr-24 pt-10 pb-10`}
			>
				<PageHeader />
				<div className='flex-1'>{children}</div>
				<PageFooter />
			</body>
		</html>
	);
}
